GET http://localhost:8000/api/projets
Content-Type: application/json

###
POST http://localhost:8000/api/projets
Content-Type: application/json

  {
    "name": "La casa de pizza",
    "picture": "https://i.ibb.co/L6BSMrW/Capture-d-e-cran-2022-02-02-a-20-54-26.png",
    "link": "https://alizeechaussonnet.github.io/La-casa-de-pizza/",
    "github": "https://github.com/AlizeeChaussonnet/La-casa-de-pizza",
    "description": "1er projet réalisé en équipe",
    "explanation": "Utilisation HTML/CSS. Inclure un effet wahoou en Javascript",
    "technos": [
      {
        "techno_name": "JavaScript"
      },  {
        "techno_name": "HTML"
      }
    ]
  }

###
POST http://localhost:8000/api/projets
Content-Type: application/json

  {
    "name": "Buzzle",
    "picture": "https://i.ibb.co/KKKDLS1/Buzzle.png",
    "link": "https://buzzle.herokuapp.com/",
    "github": "https://github.com/AlizeeChaussonnet/La-casa-de-pizza",
    "description": "2ème projet réalisé en équipe",
    "explanation": "Projet en React et utilisation d'une API + back. Réalisé avec la méthode Agile Scrum.",
    "technos": [
      {
        "techno_name": "JavaScript"
      },  {
        "techno_name": "React"
      },  {
        "techno_name": "API REST"
      },  {
        "techno_name": "ExpressJS"
      }, {
        "techno_name": "SCRUM"
      },  {
        "techno_name": "Git/GitHub"
      }
    ]
  }

###
POST http://localhost:8000/api/projets
Content-Type: application/json

  {
    "name": "SpotOn",
    "picture": "https://i.ibb.co/W59kk7m/SpotOn.png",
    "link": "http://137.74.195.166/",
    "github": " ",
    "description": "3ème projet réalisé en équipe avec un porteur de projet",
    "explanation": "Projet en React et TypeScript. Réalisation du Front-End, Back-end et Back-Office pour les utilisateurs, studios et admins. Réalisé avec la méthode Agile Scrum.",
    "technos": [
      {
        "techno_name": "TypeScript"
      },  {
        "techno_name": "React"
      },  {
        "techno_name": "API REST"
      },  {
        "techno_name": "ExpressJS"
      }, {
        "techno_name": "SCRUM"
      },  {
        "techno_name": "Git/GitHub"
      }
    ]
  }

###
PUT http://localhost:8000/api/projets/1
Content-Type: application/json

 {
     "title": "N'attendons pas - Nouvelle édition",
     "genre": "variété française",
     "picture": "picture en attente",
     "artist": "Vianney"
}

###
DELETE http://localhost:8000/api/projets/3
Content-Type: application/json
