GET http://localhost:8000/api/technos
Content-Type: application/json

###
POST http://localhost:8000/api/albums
Content-Type: application/json

 {
     "title": "N'attendons pas",
     "genre": "variété française",
     "picture": "https://boutique.totoutard.com/img/29/331812/max/p/vianney-n-attendons-pas-cd-album.jpg",
     "artist": "Vianney"
}

###
PUT http://localhost:8000/api/albums/1
Content-Type: application/json

 {
     "title": "N'attendons pas - Nouvelle édition",
     "genre": "variété française",
     "picture": "picture en attente",
     "artist": "Vianney"
}

###
GET http://localhost:8000/api/albums/1
Content-Type: application/json

###
GET http://localhost:8000/api/albums/1/tracks
Content-Type: application/json

###
DELETE http://localhost:8000/api/albums/3
Content-Type: application/json
